# Generated by Django 5.1 on 2024-08-28 17:51

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[users.validators.validate_author_age],
            ),
        ),
    ]
