# Generated by Django 5.1 on 2024-08-28 18:04

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, validators=[users.validators.validate_author_age]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
